"""update screeningroom model
:


Revision ID: 119f44ae6881
Revises: 200a01a1f3dc
Create Date: 2024-02-08 16:46:19.831862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119f44ae6881'
down_revision = '200a01a1f3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_rooms', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_rooms', sa.Column('name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
