"""add location

Revision ID: 144ac4c30f4a
Revises: 1075c228143d
Create Date: 2024-02-14 14:34:48.889585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144ac4c30f4a'
down_revision = '1075c228143d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
