"""update

Revision ID: 200a01a1f3dc
Revises: 33fdca613922
Create Date: 2024-02-07 19:31:54.995222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200a01a1f3dc'
down_revision = '33fdca613922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('public', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
