"""update

Revision ID: 531173df6462
Revises: 6fd27038435b
Create Date: 2024-02-03 20:58:44.774225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531173df6462'
down_revision = '6fd27038435b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('public', sa.Boolean(), nullable=True))
    op.drop_column('clubs', 'privacy_setting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('privacy_setting', sa.VARCHAR(), nullable=True))
    op.drop_column('clubs', 'public')
    # ### end Alembic commands ###
