"""updates

Revision ID: d28e64e40de1
Revises: 
Create Date: 2024-01-30 19:19:52.587822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28e64e40de1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('privacy_setting', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('poster_image', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('cast', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('trailer_link', sa.String(), nullable=True),
    sa.Column('streaming_availability', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_rooms')
    op.drop_table('movies')
    op.drop_table('clubs')
    # ### end Alembic commands ###
