"""add pws

Revision ID: f7cd0c64d5a1
Revises: 531173df6462
Create Date: 2024-02-04 16:13:55.880252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cd0c64d5a1'
down_revision = '531173df6462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password_hash')
    # ### end Alembic commands ###
